### ISSUE TITLE
Newbies question?

### ISSUE THREAD

**Issue by ghost** [harumo11/librealtime#1]
Hi, thanks for providing this excellent library. I've encountered some issue using it.
1. In RealtimeThread.hpp, it includes "bits/sched.h" instead of "/linux/sched.h" while the former doesn't have SCHED_DEADLINE. So I changed to the latter, I wonder if it's ok?

2. After I change the include file path to "/linux/sched.h", it does compile and run. However, I'm getting warning msg:
 "[PolicyThread] faild to setschedparam | Hi!! I'm threadOperation not permitted" 
and 
"[ERROR] Invalid param in sched_setattr() 
Did you execute with super user privilege? "

Should I ignore them or how should I fix them? Thanks!

**Comment by harumo11** [comment]
Hi, @szcnc. Thank you for taking look for this library.

1. Put simply, It should good. RealtimeThread.hpp assumes using linux/sched.h.
In my environment (Ubuntu 18.04/ Linux Mint 19.2 and clang-6.0), programs are compiled with linux/shed.h implicitly.

2. Try to run your program with super user privilege like following.
    ```
    sudo ./your_program_name
    ```
You can also ignore that message. In that case, your program will behave as `std::thread`.

Thanks!

**Comment by ghost** [comment]
Hi @harumo11. Thanks a lot for replying.

1. In my environment(Ubuntu 16.04/clang version 3.8.0-2ubuntu4), it is compiling with the wrong "sched.h". 

2. Probably std::thread is not what I expected. I believe it still has to do with the wrong "sched.h". 

Thanks again for your help!
